#!/usr/bin/env bash
# scripts/deploy_backend.sh
#
# Reproducible deploy of the FastAPI backend to Firebase Cloud Functions
# (project: lyzr-ai-demo). Designed to be the single command you run after
# editing anything under backend/ — it stages source, regenerates the Python
# requirements, and deploys functions + hosting via the pinned firebase-tools
# CLI (see root package.json).
#
# What it does, in order:
#   1. Verifies firebase.json / .firebaserc / backend / firebase dirs.
#   2. Installs firebase-tools (yarn, from root package.json) if missing.
#   3. Stages backend/*.py → firebase/_backend/ (rsync-style; fresh each run).
#   4. Generates firebase/requirements.txt by concatenating
#      firebase/requirements.txt.in with backend/requirements.txt
#      (uvicorn stripped — Firebase provides the HTTP server).
#   5. Runs `firebase deploy --only functions:api,hosting`.
#
# One-time setup (manual, do NOT script):
#   A. yarn install                  # at repo root, installs firebase-tools
#   B. npx firebase login
#   C. Upgrade Firebase project to Blaze (Cloud Functions requires PAYG)
#   D. Set runtime secrets (Lyzr credentials):
#        npx firebase functions:secrets:set LYZR_API_KEY  --project lyzr-ai-demo
#        npx firebase functions:secrets:set LYZR_AGENT_ID --project lyzr-ai-demo
#   E. Add custom domain `lyzr-api.archlife.org` in Hosting console
#      and publish the DNS records Firebase issues (one-time, ~15-60 min
#      for SSL provisioning).
#
# Usage:
#   ./scripts/deploy_backend.sh                # deploy
#   ./scripts/deploy_backend.sh --stage-only   # stage files, skip deploy
#   ./scripts/deploy_backend.sh --project foo  # override project id

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# ─── flags ────────────────────────────────────────────────────────────────────
STAGE_ONLY=0
PROJECT_OVERRIDE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --stage-only) STAGE_ONLY=1; shift ;;
    --project)    PROJECT_OVERRIDE="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,30p' "$0"; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

# ─── colors ───────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  C=$'\033[38;5;87m'; G=$'\033[38;5;120m'; Y=$'\033[38;5;221m'; R=$'\033[38;5;203m'; D=$'\033[0m'
else
  C=""; G=""; Y=""; R=""; D=""
fi
say()  { printf '%s▸%s %s\n' "$C" "$D" "$*"; }
ok()   { printf '%s✓%s %s\n' "$G" "$D" "$*"; }
warn() { printf '%s!%s %s\n' "$Y" "$D" "$*" >&2; }
die()  { printf '%s✗%s %s\n' "$R" "$D" "$*" >&2; exit 1; }

# ─── prereqs ──────────────────────────────────────────────────────────────────
[[ -f firebase.json ]] || die "firebase.json missing at $ROOT_DIR"
[[ -f .firebaserc   ]] || die ".firebaserc missing at $ROOT_DIR"
[[ -d backend       ]] || die "backend/ missing"
[[ -d firebase      ]] || die "firebase/ missing"
[[ -f backend/main.py ]] || die "backend/main.py missing (FastAPI entry)"
[[ -f backend/requirements.txt ]] || die "backend/requirements.txt missing"

if [[ ! -x node_modules/.bin/firebase ]]; then
  say "firebase-tools not installed — running 'yarn install' at repo root"
  command -v yarn >/dev/null || die "yarn not found. Install Node + yarn, then re-run."
  yarn install
fi
FIREBASE="$ROOT_DIR/node_modules/.bin/firebase"

# ─── stage backend → firebase/_backend ────────────────────────────────────────
say "Staging backend/*.py → firebase/_backend/"
rm -rf firebase/_backend
mkdir -p firebase/_backend
# Python sources only; skip caches, venv, env files.
find backend -maxdepth 1 -type f -name "*.py" -exec cp -p {} firebase/_backend/ \;
# Make it importable as a package (firebase/main.py imports `_backend.main`).
: > firebase/_backend/__init__.py
ok "Staged $(find firebase/_backend -maxdepth 1 -name '*.py' | wc -l | tr -d ' ') Python file(s)"

# ─── generate firebase/requirements.txt ───────────────────────────────────────
say "Generating firebase/requirements.txt"
{
  echo "# Generated by scripts/deploy_backend.sh — DO NOT edit by hand."
  echo "# Source: firebase/requirements.txt.in + backend/requirements.txt"
  echo
  cat firebase/requirements.txt.in
  echo
  echo "# === inherited from backend/requirements.txt ==="
  # Drop blank lines, comments, and uvicorn (Firebase provides the server).
  grep -Ev '^\s*$|^\s*#|^uvicorn(\[|$|>|=)' backend/requirements.txt
} > firebase/requirements.txt
ok "Wrote firebase/requirements.txt"

# ─── build firebase/venv ──────────────────────────────────────────────────────
# Firebase Functions CLI introspects the Python source through a local venv
# (firebase/venv/bin/python) — it imports main.py to discover decorated
# handlers. The venv must exist and contain every dep imported by main.py,
# even though Cloud Build re-resolves at deploy time from requirements.txt.
#
# The runtime in firebase.json is python312, so we prefer python3.12 locally
# to keep ABI/wheel compatibility tight. We fall back to 3.11 / 3.13 only if
# 3.12 isn't installed.
PY_BIN=""
for cand in python3.12 python3.13 python3.11 python3.10; do
  if command -v "$cand" >/dev/null 2>&1; then PY_BIN="$cand"; break; fi
done
[[ -n "$PY_BIN" ]] || die "No suitable Python found (need 3.10–3.13)."
PY_VER="$("$PY_BIN" -c 'import sys;print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

VENV="firebase/venv"
VENV_PY_VER_FILE="$VENV/.py-version"
if [[ -x "$VENV/bin/python" && -f "$VENV_PY_VER_FILE" && "$(cat "$VENV_PY_VER_FILE")" == "$PY_VER" ]]; then
  : # reuse existing venv
else
  say "Creating firebase/venv with $PY_BIN ($PY_VER)"
  rm -rf "$VENV"
  "$PY_BIN" -m venv "$VENV"
  echo "$PY_VER" > "$VENV_PY_VER_FILE"
fi

# Install deps only if requirements.txt changed since last install.
HASH_FILE="$VENV/.deps-hash"
NEW_HASH="$(shasum -a 256 firebase/requirements.txt | awk '{print $1}')"
if [[ ! -f "$HASH_FILE" || "$(cat "$HASH_FILE")" != "$NEW_HASH" ]]; then
  say "Installing Python deps into firebase/venv (this can take a minute)"
  "$VENV/bin/python" -m pip install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet -r firebase/requirements.txt
  echo "$NEW_HASH" > "$HASH_FILE"
  ok "venv ready"
else
  ok "venv up-to-date (deps unchanged)"
fi

if [[ "$STAGE_ONLY" == "1" ]]; then
  ok "--stage-only: skipping deploy."
  exit 0
fi

# ─── deploy ───────────────────────────────────────────────────────────────────
if [[ -n "$PROJECT_OVERRIDE" ]]; then
  PROJECT="$PROJECT_OVERRIDE"
else
  PROJECT="$(python3 -c "import json,sys;print(json.load(open('.firebaserc'))['projects']['default'])")"
fi
say "Deploying to Firebase project: ${PROJECT}"
"$FIREBASE" deploy --only functions:api,hosting --project "$PROJECT"

ok "Deploy complete."
cat <<EOF

  Default URLs:
    https://${PROJECT}.web.app/api/health
    https://${PROJECT}.firebaseapp.com/api/health

  Custom domain (once DNS + SSL are provisioned in Firebase Hosting):
    https://lyzr-api.archlife.org/api/health

  Next: set frontend/wrangler.jsonc → vars.BACKEND_URL = https://lyzr-api.archlife.org
        then redeploy the Pages site.
EOF
